app = "telegram-number-bot"
primary_region = "ams"

[build]
  dockerfile = "Dockerfile"

[env]
  TELEGRAM_TOKEN = "8480004036:AAHPjL-RiItdX6eT-QKyBopkxpfrmA2aDVs"
  GOOGLE_AI_API_KEY = "AIzaSyAbK4LMlTsR2MxlG5R76Nlx6RJIyAD_FhY"

[[processes]]
  name = "bot"
  cmd = "python aibot.py"
